// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:e0b91e33-d45b-414e-a0c6-76068f7de6d1',
    'aws_cognito_region': 'us-east-1',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '2264021383a248e1869a50344d82d799',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '3dc83b23-047e-47fa-9d9f-da2cb83d4435',
    'aws_project_name': 'DivotReactNative',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'divotreactnative-mobilehub-1253509601',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_kdMWMZxSr',
    'aws_user_pools_mfa_type': 'OPTIONAL',
    'aws_user_pools_web_client_id': '1a2q7hja3aj7fpcopoiq8ofqf',
}

export default awsmobile;
